### ISSUE TITLE
Checklist

### ISSUE THREAD

**Issue by viktorsmari** [reflow-project/weloop#2]
## Basic user management flows
- [x] Check / Confirm: USER - can signup, login and recover password
- [x] USER - can edit profile information.
   * (Profile image change does not work on localhost)
- [x] USER - can create communities
- [x] USER - can find other communities
- [x] USER - can join communities
- [x] USER - can discover other users that are part of the network
- [x] USER - can follow / unfollow other users and receive updates from their activities
- [x] USER - can create **resources**

## Basic resource management

- [x] USER - can publish an offer or intent (former "request") of an available resource or skill

## Resource creation

User can:
- [x] create a resource 
- [x] create a skill

## Communities

- [x] Users can post messages in Discussions / threads

## Advanced resource management

User can:
- [ ] create custom taxonomies
- [ ] subscribe to one or more taxonomies, to receive notifications each time a resource has been classified with one of them
- [ ] start a thread on an existing offer/intent (former "request")

## Intents creation

User can:
- [x] create & query basic intents (with name, description, image) + context (group/organisation)
- [ ] update & (soft)delete basic intents
- [ ] group intents into a process to fulfill a particular intent (former "request")

## Inventory tracking

User can:
- [x]  add a resource on the inventory
- [ ]  track the transfer of a resource to another agent zenroom
- [ ]  track the production of a new resource
- [x]  track the consumption of a new resource
- [x]  track the usage of a resource
- [x]  trace back all activities that are connected to a particular resource
